# -*- coding: utf-8 -*-
"""GMM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2Nv1wSYy5dpkL385w7-C4HCePehyY66
"""

!pip install ultralytics

import cv2
import numpy as np
import matplotlib.pyplot as plt

from ultralytics import YOLO

# تحميل النموذج الجاهز

model = YOLO('yolov8n.pt')

from google.colab import files

uploaded = files.upload()

import os

os.listdir()

image_path = '000000000094.jpg'

img = cv2.imread(image_path)

img_rgb = cv2.cvtColor(
    img,
    cv2.COLOR_BGR2RGB
)

plt.figure(figsize=(8,8))

plt.imshow(img_rgb)

plt.axis('off')

plt.show()

results = model(image_path)

results[0].show()



"""# المرحلة 1 — استخراج Features من YOLO"""

features = results[0].boxes.xywh.cpu().numpy()

print("Features Shape:")

print(features.shape)

print(features[:5])

plt.figure(figsize=(8,5))

plt.scatter(
    features[:,0],
    features[:,1]
)

plt.title("Extracted Features")

plt.xlabel("X")

plt.ylabel("Y")

plt.show()

"""# Gaussian"""

def gaussian_pdf(x, mean, cov):

    n = len(mean)

    cov = cov + np.eye(n) * 1e-6

    det = np.linalg.det(cov)

    inv = np.linalg.inv(cov)

    norm_const = 1.0 / (
        np.power((2 * np.pi), n / 2) *
        np.sqrt(det)
    )

    x_mu = x - mean

    result = np.exp(
        -0.5 * np.dot(
            np.dot(x_mu, inv),
            x_mu.T
        )
    )

    return norm_const * result

K = 2



N = len(features)


means = features[
    np.random.choice(
        N,
        K,
        replace=False
    )
]



covariances = [
    np.cov(features.T)
    for _ in range(K)
]



pis = np.ones(K) / K

# E-Step

def expectation_step(
    X,
    means,
    covariances,
    pis
):

    N = len(X)

    K = len(means)

    responsibilities = np.zeros((N, K))

    for i in range(N):

        for k in range(K):

            responsibilities[i, k] = (
                pis[k] *
                gaussian_pdf(
                    X[i],
                    means[k],
                    covariances[k]
                )
            )

        responsibilities[i] /= (
            np.sum(responsibilities[i]) + 1e-6
        )

    return responsibilities

"""# M_step"""

def maximization_step(
    X,
    responsibilities
):

    N, D = X.shape

    K = responsibilities.shape[1]

    means = np.zeros((K, D))

    covariances = []

    pis = np.zeros(K)

    for k in range(K):

        Nk = np.sum(
            responsibilities[:, k]
        )

        means[k] = (
            np.sum(
                responsibilities[:, k][:, np.newaxis] * X,
                axis=0
            ) / Nk
        )

        cov = np.zeros((D, D))

        for i in range(N):

            diff = (
                X[i] - means[k]
            ).reshape(-1, 1)

            cov += (
                responsibilities[i, k] *
                np.dot(diff, diff.T)
            )

        cov /= Nk

        covariances.append(cov)

        pis[k] = Nk / N

    return means, covariances, pis

"""# EM Algorithm."""

log_likelihoods = []

for epoch in range(20):

    # E-Step
    responsibilities = expectation_step(
        features,
        means,
        covariances,
        pis
    )

    # M-Step
    means, covariances, pis = maximization_step(
        features,
        responsibilities
    )

    # حساب Log Likelihood
    ll = 0

    for x in features:

        temp = 0

        for k in range(K):

            temp += (
                pis[k] *
                gaussian_pdf(
                    x,
                    means[k],
                    covariances[k]
                )
            )

        ll += np.log(temp + 1e-6)

    log_likelihoods.append(ll)

    print(
        f"Epoch {epoch+1}, Log Likelihood: {ll}"
    )

plt.figure(figsize=(8,5))

plt.plot(log_likelihoods)

plt.title("Log Likelihood vs Epochs")

plt.xlabel("Epoch")

plt.ylabel("Log Likelihood")

plt.show()

nll_scores = []

for x in features:

    prob = 0

    for k in range(K):

        prob += (
            pis[k] *
            gaussian_pdf(
                x,
                means[k],
                covariances[k]
            )
        )

    nll = -np.log(prob + 1e-6)

    nll_scores.append(nll)

print(nll_scores)

plt.figure(figsize=(8,5))

plt.hist(
    nll_scores,
    bins=10
)

plt.title("NLL Distribution")

plt.xlabel("Negative Log Likelihood")

plt.ylabel("Frequency")

plt.show()

